### ISSUE TITLE
CGRect midPoint

### ISSUE THREAD

**Issue by ghost** [trifork/TriforkSwiftExtensions#7]
```
public var midPoint: CGPoint {
    return CGPoint(x: self.midX, y: self.midY)
}
```

**Comment by tkctrifork** [comment]
@kimdv I think you misunderstood the purpose of this feature 😜 You implemented a halving of a `CGPoint` which does not make sense in most cases. The idea was to implement the `midPoint` on a `CGRect`, such that you get the center point of a rect, where the original `x` and `y` properties are taken into account. The implementation in the original issue should actually be good enough, since the `midX` and `midY` properties do exist on the `CGRect` struct.

**Comment by kimdv** [comment]
@tkctrifork can be closed
